"use client";

import Image from "next/image";
import { Plus, Radio, Search } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { SiteImageFields } from "../../components/site-image-fields";
import Toast, { type ToastVariant } from "../../components/toast";
import { Button } from "../../components/ui/button";
import { ConfirmationDialog } from "../../components/ui/confirmation-dialog";
import { Input, Textarea } from "../../components/ui/form-controls";
import { Pagination } from "../../components/ui/pagination";
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "../../components/ui/surfaces";
import { apiClient, isApiError } from "../../lib/api-client";
import { normalizeYouTubeEmbedUrl, YOUTUBE_EMBED_ERROR, YOUTUBE_EMBED_HELP } from "../../lib/youtube-embed";
import type { PaginatedResponse } from "../../types/api";

interface Program { id:string; title:string; description:string; coverImage:string; externalCoverImage?:string; presenter:string; promoVideoUrl:string; is_active:boolean }
type ToastState={message:string;variant:ToastVariant}|null;
const emptyPage:PaginatedResponse<Program>={count:0,next:null,previous:null,results:[]};

export default function ProgramsPage(){
  const [data,setData]=useState(emptyPage);const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [pageLoading,setPageLoading]=useState(false);const [loadError,setLoadError]=useState("");const [retrying,setRetrying]=useState(false);
  const [showForm,setShowForm]=useState(false);const [editing,setEditing]=useState<Program|null>(null);const [title,setTitle]=useState("");const [presenter,setPresenter]=useState("");const [description,setDescription]=useState("");const [coverImage,setCoverImage]=useState("");const [promoVideoUrl,setPromoVideoUrl]=useState("");const [isActive,setIsActive]=useState(true);const [selectedFile,setSelectedFile]=useState<File|null>(null);const [submitting,setSubmitting]=useState(false);const [fieldErrors,setFieldErrors]=useState<Record<string,string[]>>({});const [formError,setFormError]=useState("");
  const [deleteTarget,setDeleteTarget]=useState<Program|null>(null);const [deleting,setDeleting]=useState(false);const [deleteError,setDeleteError]=useState("");const [toast,setToast]=useState<ToastState>(null);

  const loadPrograms=useCallback(async(targetPage:number,query:string,signal?:AbortSignal)=>{const params=new URLSearchParams({page:String(targetPage),ordering:"title"});if(query.trim())params.set("search",query.trim());return apiClient.get<PaginatedResponse<Program>>(`/api/programs?${params}`,{signal});},[]);
  const refresh=useCallback(async()=>{setRetrying(true);setLoadError("");try{setData(await loadPrograms(page,search));}catch(error){if(isApiError(error))setLoadError(error.message);else setLoadError("Unable to reach the programs service.");}finally{setRetrying(false);setLoading(false);setPageLoading(false);}},[loadPrograms,page,search]);
  useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>{setPageLoading(true);loadPrograms(page,search,controller.signal).then((response)=>{setData(response);setLoadError("");setLoading(false);}).catch((error:unknown)=>{if(error instanceof DOMException&&error.name==="AbortError")return;setLoadError(isApiError(error)?error.message:"Unable to reach the programs service.");setLoading(false);}).finally(()=>setPageLoading(false));},250);return()=>{window.clearTimeout(timer);controller.abort();};},[loadPrograms,page,search]);

  const clearForm=()=>{setTitle("");setPresenter("");setDescription("");setCoverImage("");setPromoVideoUrl("");setIsActive(true);setSelectedFile(null);setEditing(null);setFieldErrors({});setFormError("");setShowForm(false);};
  const startEdit=(program:Program)=>{setEditing(program);setTitle(program.title);setPresenter(program.presenter);setDescription(program.description);setCoverImage(program.externalCoverImage||"");setPromoVideoUrl(program.promoVideoUrl||"");setIsActive(program.is_active);setSelectedFile(null);setFieldErrors({});setFormError("");setShowForm(true);};
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(submitting)return;const normalizedPromo=normalizeYouTubeEmbedUrl(promoVideoUrl);if(normalizedPromo===null){setFieldErrors({promo_video_url:[YOUTUBE_EMBED_ERROR]});return;}setSubmitting(true);setFieldErrors({});setFormError("");const form=new FormData();if(editing)form.set("id",editing.id);form.set("is_active",String(isActive));form.set("title",title);form.set("presenter",presenter);form.set("description",description);form.set("promo_video_url",normalizedPromo);if(coverImage)form.set("cover_image",coverImage);if(selectedFile)form.set("uploaded_cover_image",selectedFile);try{await (editing?apiClient.put<Program>("/api/programs",form):apiClient.post<Program>("/api/programs",form));setToast({message:editing?"Program updated successfully.":"Program created successfully.",variant:"success"});clearForm();if(!editing&&page!==1)setPage(1);else await refresh();}catch(error){if(isApiError(error)){setFieldErrors(error.fieldErrors||{});setFormError(error.message);}else setFormError("Unable to save the program. Please try again.");}finally{setSubmitting(false);}};
  const remove=async()=>{if(!deleteTarget||deleting)return;setDeleting(true);setDeleteError("");try{await apiClient.delete<void>(`/api/programs?id=${encodeURIComponent(deleteTarget.id)}`);setToast({message:`${deleteTarget.title} was deleted.`,variant:"success"});setDeleteTarget(null);if(data.results.length===1&&page>1)setPage((value)=>value-1);else await refresh();}catch(error){setDeleteError(isApiError(error)?error.message:"Unable to delete the program. Please try again.");}finally{setDeleting(false);}};

  const primaryAction=<div className="flex flex-wrap items-end gap-3"><Button icon={<Plus aria-hidden="true"/>} onClick={()=>showForm?clearForm():setShowForm(true)}>{showForm?"Dismiss form":"Add program"}</Button><div className="flex flex-wrap gap-1" aria-label="Program visibility">{data.results.map((program)=><span key={program.id} className="inline-flex items-center gap-1 text-xs text-slate-300">{program.title}<StatusBadge status={program.is_active?"active":"inactive"} label={program.is_active?"Active":"Inactive"}/></span>)}</div>{showForm&&<label className="text-xs text-slate-300">Public visibility<select className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-2 text-white" value={isActive?"active":"inactive"} onChange={(event)=>setIsActive(event.target.value==="active")} disabled={submitting} aria-describedby="program-visibility-help"><option value="active">Active — visible publicly</option><option value="inactive">Inactive — hidden publicly</option></select><StatusBadge status={isActive?"active":"inactive"} label={isActive?"Active":"Inactive"}/><span id="program-visibility-help" className="sr-only">Inactive Programs are removed from public Programs and Program filters; child Episodes are not changed.</span></label>}</div>;
  const promoPreview=normalizeYouTubeEmbedUrl(promoVideoUrl);
  return <div className="space-y-6 view-fade"><Toast message={toast?.message||null} variant={toast?.variant} onDismiss={()=>setToast(null)}/><PageHeader title="Radio Programs" description="Manage CBM Radio program channels." primaryAction={primaryAction}/>
    <div className="program-search"><Input label="Search programs" value={search} onChange={(event)=>{setSearch(event.target.value);setPage(1);}} placeholder="Search title or presenter"/><Search aria-hidden="true"/></div>
    {showForm&&<Card className="program-form-card"><form onSubmit={save} className="program-form"><div><Input label="Program title" required value={title} onChange={(event)=>setTitle(event.target.value)} error={fieldErrors.title?.[0]} disabled={submitting}/><Input label="Presenter name" required value={presenter} onChange={(event)=>setPresenter(event.target.value)} error={fieldErrors.presenter?.[0]} disabled={submitting}/><SiteImageFields currentUrl={editing?.coverImage} externalUrl={coverImage} file={selectedFile} onExternalUrlChange={setCoverImage} onFileChange={setSelectedFile}/></div><div><Textarea label="Description" rows={6} value={description} onChange={(event)=>setDescription(event.target.value)} error={fieldErrors.description?.[0]} disabled={submitting}/><Input label="YouTube Embed URL" type="url" value={promoVideoUrl} onChange={(event)=>{setPromoVideoUrl(event.target.value);setFieldErrors((current)=>({...current,promo_video_url:[]}));}} helperText={YOUTUBE_EMBED_HELP} error={fieldErrors.promo_video_url?.[0]} disabled={submitting}/>{promoPreview&&<div className="video-embed-preview"><iframe src={promoPreview} title={`${title||"Program"} promo preview`} allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>}{formError&&<p className="ui-field-error" role="alert">{formError}</p>}<div className="program-form-actions"><Button variant="outline" onClick={clearForm} disabled={submitting}>Cancel</Button><Button type="submit" loading={submitting} loadingLabel={editing?"Updatingâ€¦":"Creatingâ€¦"}>{editing?"Update program":"Create program"}</Button></div></div></form></Card>}
    {loading?<LoadingState label="Fetching radio programsâ€¦"/>:loadError&&!data.results.length?<ErrorState message={loadError} onRetry={()=>void refresh()} retrying={retrying}/>:data.results.length===0?<EmptyState icon={<Radio/>} title={search?"No matching programs":"No programs yet"} description={search?"Try another search term.":"Create the first program to begin."} action={!search&&primaryAction}/>:<><div className={`program-grid ${pageLoading?"is-loading":""}`} aria-busy={pageLoading}>{data.results.map((program)=><Card key={program.id} className="program-card">{program.coverImage?<div className="program-image"><Image src={program.coverImage} alt="" fill unoptimized className="object-cover"/></div>:<div className="program-image program-image-empty"><Radio aria-hidden="true"/></div>}<div className="program-card-body"><div><h2>{program.title}</h2><p className="program-presenter">Presented by {program.presenter}</p><p>{program.description||"No description provided."}</p></div><div className="program-card-actions"><Button variant="ghost" onClick={()=>startEdit(program)}>Edit</Button><Button variant="ghost" className="program-delete-button" onClick={()=>{setDeleteError("");setDeleteTarget(program);}}>Delete</Button></div></div></Card>)}</div>{loadError&&<ErrorState message={loadError} onRetry={()=>void refresh()} retrying={retrying}/>}<Pagination count={data.count} currentPage={page} hasNext={Boolean(data.next)} hasPrevious={Boolean(data.previous)} loading={pageLoading} onNext={()=>setPage((value)=>value+1)} onPrevious={()=>setPage((value)=>Math.max(1,value-1))}/></>}
    <ConfirmationDialog open={Boolean(deleteTarget)} title="Delete program?" description={deleteTarget?`Delete â€œ${deleteTarget.title}â€? This action cannot be undone.`:""} loading={deleting} error={deleteError} onConfirm={()=>void remove()} onCancel={()=>{if(!deleting){setDeleteTarget(null);setDeleteError("");}}}/>
  </div>;
}
