"use client";

import { useId, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";

type FieldFrameProps = { id:string; label:string; required?:boolean; helperText?:string; error?:string; children:ReactNode };
export function FormField({ id, label, required, helperText, error, children }: FieldFrameProps) { const describedBy=[helperText&&`${id}-help`,error&&`${id}-error`].filter(Boolean).join(" ")||undefined; return <div className="ui-form-field"><label htmlFor={id}>{label}{required && <span aria-hidden="true"> *</span>}</label>{children && <div data-describedby={describedBy}>{children}</div>}{helperText && <p id={`${id}-help`} className="ui-field-help">{helperText}</p>}{error && <p id={`${id}-error`} className="ui-field-error" role="alert">{error}</p>}</div>; }

type BaseFieldProps = { label:string; helperText?:string; error?:string };
export function Input({ label, helperText, error, id:providedId, required, className="", ...props }: BaseFieldProps & InputHTMLAttributes<HTMLInputElement>) { const generated=useId(); const id=providedId||generated; const describedBy=[helperText&&`${id}-help`,error&&`${id}-error`].filter(Boolean).join(" ")||undefined; return <div className="ui-form-field"><label htmlFor={id}>{label}{required&&<span aria-hidden="true"> *</span>}</label><input id={id} required={required} aria-invalid={Boolean(error)||undefined} aria-describedby={describedBy} className={`ui-input ${className}`} {...props}/>{helperText&&<p id={`${id}-help`} className="ui-field-help">{helperText}</p>}{error&&<p id={`${id}-error`} className="ui-field-error" role="alert">{error}</p>}</div>; }
export function Textarea({ label, helperText, error, id:providedId, required, className="", ...props }: BaseFieldProps & TextareaHTMLAttributes<HTMLTextAreaElement>) { const generated=useId(); const id=providedId||generated; const describedBy=[helperText&&`${id}-help`,error&&`${id}-error`].filter(Boolean).join(" ")||undefined; return <div className="ui-form-field"><label htmlFor={id}>{label}{required&&<span aria-hidden="true"> *</span>}</label><textarea id={id} required={required} aria-invalid={Boolean(error)||undefined} aria-describedby={describedBy} className={`ui-input ${className}`} {...props}/>{helperText&&<p id={`${id}-help`} className="ui-field-help">{helperText}</p>}{error&&<p id={`${id}-error`} className="ui-field-error" role="alert">{error}</p>}</div>; }
export function Select({ label, helperText, error, id:providedId, required, className="", children, ...props }: BaseFieldProps & SelectHTMLAttributes<HTMLSelectElement>) { const generated=useId(); const id=providedId||generated; const describedBy=[helperText&&`${id}-help`,error&&`${id}-error`].filter(Boolean).join(" ")||undefined; return <div className="ui-form-field"><label htmlFor={id}>{label}{required&&<span aria-hidden="true"> *</span>}</label><select id={id} required={required} aria-invalid={Boolean(error)||undefined} aria-describedby={describedBy} className={`ui-input ${className}`} {...props}>{children}</select>{helperText&&<p id={`${id}-help`} className="ui-field-help">{helperText}</p>}{error&&<p id={`${id}-error`} className="ui-field-error" role="alert">{error}</p>}</div>; }
export function Checkbox({ label, helperText, error, id:providedId, ...props }: BaseFieldProps & InputHTMLAttributes<HTMLInputElement>) { const generated=useId(); const id=providedId||generated; return <div className="ui-form-field"><label className="ui-checkbox" htmlFor={id}><input id={id} type="checkbox" aria-invalid={Boolean(error)||undefined} aria-describedby={helperText?`${id}-help`:undefined} {...props}/><span>{label}</span></label>{helperText&&<p id={`${id}-help`} className="ui-field-help">{helperText}</p>}{error&&<p className="ui-field-error" role="alert">{error}</p>}</div>; }
