import type { ReactNode } from "react";

export function PageHeader({ title, description, primaryAction, secondaryAction }: { title:string; description?:string; primaryAction?:ReactNode; secondaryAction?:ReactNode }) { return <header className="ui-page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{(primaryAction || secondaryAction) && <div>{secondaryAction}{primaryAction}</div>}</header>; }
export function Card({ children, className="" }: { children:ReactNode; className?:string }) { return <section className={`ui-card ${className}`}>{children}</section>; }
export function LoadingState({ label="Loading…", compact=false }: { label?:string; compact?:boolean }) { return <div className={`ui-state ${compact ? "is-compact" : ""}`} role="status" aria-live="polite"><span className="dashboard-spinner" aria-hidden="true" /><span>{label}</span></div>; }
export function EmptyState({ title, description, action, icon }: { title:string; description?:string; action?:ReactNode; icon?:ReactNode }) { return <section className="ui-state"><span aria-hidden="true">{icon}</span><h2>{title}</h2>{description && <p>{description}</p>}{action}</section>; }
export function ErrorState({ title="Something went wrong", message, onRetry, retrying=false, detail }: { title?:string; message:string; onRetry?:()=>void; retrying?:boolean; detail?:string }) { return <section className="ui-state ui-error-state" role="alert"><h2>{title}</h2><p>{message}</p>{process.env.NODE_ENV === "development" && detail && <details><summary>Technical detail</summary><code>{detail}</code></details>}{onRetry && <button type="button" onClick={onRetry} disabled={retrying}>{retrying ? "Retrying…" : "Try again"}</button>}</section>; }
const statusClasses:Record<string,string>={active:"success",published:"success",approved:"success",inactive:"muted",draft:"muted",featured:"info",pending:"warning",error:"error"};
export function StatusBadge({ status, label }: { status:"active"|"inactive"|"published"|"draft"|"featured"|"pending"|"approved"|"error"; label?:string }) { return <span className={`ui-status ui-status-${statusClasses[status]}`}>{label || status}</span>; }
